# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DenySelfApprove < Formula
  desc "Deny self-approved GitHub Pull Requests.
"
  homepage "https://github.com/suzuki-shunsuke/deny-self-approve"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/suzuki-shunsuke/deny-self-approve/releases/download/v0.3.0/deny-self-approve_darwin_amd64.tar.gz"
      sha256 "46877dff2719318d940d617d7d67c6cd3a82c98d84d5a99f653e6afa8544f57b"

      def install
        bin.install "deny-self-approve"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/suzuki-shunsuke/deny-self-approve/releases/download/v0.3.0/deny-self-approve_darwin_arm64.tar.gz"
      sha256 "11c6a204c23e35c8864332bcd3cc564a3b6f57c402f996f11085bd01568fd203"

      def install
        bin.install "deny-self-approve"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/suzuki-shunsuke/deny-self-approve/releases/download/v0.3.0/deny-self-approve_linux_amd64.tar.gz"
        sha256 "c6c46279da8e10d147aef5dfdc8f988d33a6418978b9931aa3c8d3d1d5cb399b"

        def install
          bin.install "deny-self-approve"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/suzuki-shunsuke/deny-self-approve/releases/download/v0.3.0/deny-self-approve_linux_arm64.tar.gz"
        sha256 "ca8f4f867965abf93d3c4b101072223048048e994a753cdf93db7b89136bf571"

        def install
          bin.install "deny-self-approve"
        end
      end
    end
  end

  test do
    system "#{bin}/deny-self-approve --version"
  end
end
